config/routes.rb
Sorveteria::Application.routes.draw do
  resources :produtos

  resources :protudos

  resources :sorvetes
  root :to => "sorvetes#index"

end

app/models/produto.rb
class Produto < ActiveRecord::Base
  attr_accessible :nome, :preco, :tipo

  validates_presence_of :nome, message: "deve ser preenchido"
  validates_presence_of :nome, preco: "deve ser preenchido"

  belongs_to :sorvetes
end

app/models/sorvete.rb
class Sorvete < ActiveRecord::Base
  attr_accessible :cobertura, :preco, :sabor, :tipo_id

  has_many :produtos

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sorvetes_controller.rb
class SorvetesController < ApplicationController
  # GET /sorvetes
  # GET /sorvetes.json
  def index
    @sorvetes = Sorvete.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sorvetes }
    end
  end

  # GET /sorvetes/1
  # GET /sorvetes/1.json
  def show
    @sorvete = Sorvete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sorvete }
    end
  end

  # GET /sorvetes/new
  # GET /sorvetes/new.json
  def new
    @sorvete = Sorvete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sorvete }
    end
  end

  # GET /sorvetes/1/edit
  def edit
    @sorvete = Sorvete.find(params[:id])
  end

  # POST /sorvetes
  # POST /sorvetes.json
  def create
    @sorvete = Sorvete.new(params[:sorvete])

    respond_to do |format|
      if @sorvete.save
        format.html { redirect_to @sorvete, notice: 'Sorvete was successfully created.' }
        format.json { render json: @sorvete, status: :created, location: @sorvete }
      else
        format.html { render action: "new" }
        format.json { render json: @sorvete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sorvetes/1
  # PUT /sorvetes/1.json
  def update
    @sorvete = Sorvete.find(params[:id])

    respond_to do |format|
      if @sorvete.update_attributes(params[:sorvete])
        format.html { redirect_to @sorvete, notice: 'Sorvete was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sorvete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sorvetes/1
  # DELETE /sorvetes/1.json
  def destroy
    @sorvete = Sorvete.find(params[:id])
    @sorvete.destroy

    respond_to do |format|
      format.html { redirect_to sorvetes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sorvetes_helper.rb
module SorvetesHelper
end

app/views/layouts/application.html.haml
%title Sorveteria
= stylesheet_link_tag    "application", :media => "all"
= javascript_include_tag "application"
= csrf_meta_tags
= yield

app/views/produtos/_form.html.haml
= semantic_form_for @produto do |f|
   = f.inputs do
      = f.input :nome 
      = f.input :tipo 
      = f.input :preco

   = f.actions do
      = f.action :submit, :as => :input

app/views/produtos/edit.html.haml
%h1 Editing produto
= render 'form'

= link_to 'Mostrar', @produto 
= link_to 'Voltar', produtos_path

app/views/produtos/index.html.haml
%h1 Lista de produtos

%table
  %tr
    %th Nome
    %th Tipo
    %th Preco
    %th
    %th
    %th

- @produtos.each do |produto|
  %tr
    %td= produto.nome
    %td= produto.tipo
    %td= produto.preco
    %td= link_to 'Mostrar', produto
    %td= link_to 'Editar', edit_produto_path(produto)
    %td= link_to 'Deletar', produto, method: :delete, data: { confirm: 'Voce tem certeza?' }

%br
= link_to 'Novo Produto', new_produto_path

app/views/produtos/new.html.haml
%h1 Novo produto

= render 'form'

= link_to 'Voltar', produtos_path

app/views/produtos/show.html.haml
#notice= notice 

%p
  %b Nome:
  = @produto.nome


%p
  %b Tipo:
  = @produto.tipo

%p
  %b Preco:
  = @produto.preco



= link_to 'Editar', edit_produto_path(@produto)
= link_to 'Voltar', produtos_path

app/views/sorvetes/_form.html.haml
= semantic_form_for @sorvete do |f|
  = f.inputs do
    = f.input :sabor
    = f.input :preco
    = f.input :cobertura, :as => :radio,
     :label => "Cobertura", :collection => [["Sim", true], ["Nao", false]]
  = f.button

app/views/sorvetes/edit.html.haml
%h1 Editando Sorvetes

= render 'form'

= link_to 'Mostrar', @sorvete 
= link_to 'Voltar', sorvetes_path

app/views/sorvetes/index.html.haml
%h1 Lista de Sorvetes

%table
  %tr
    %th Sabor
    %th Preco
    %th Cobertura
    %th
    %th

- @sorvetes.each do |sorvete|
  %tr
    %td= sorvete.sabor
    %td= sorvete.preco
    %td= sorvete.cobertura
    %td= link_to 'Mostrar', sorvete
    %td= link_to 'Editar', edit_sorvete_path(sorvete)
    /*%td= link_to 'Destroy', sorvete, method: :delete, data: { confirm: 'Esta certo disso?' }*/

%br
= link_to 'Novo Sorvete', new_sorvete_path

app/views/sorvetes/new.html.haml
%h1 Novo Sorvete

= render 'form'

= link_to 'Voltar', sorvetes_path

app/views/sorvetes/show.html.haml
#notice= notice

%p
  %b Sabor:
  = @sorvete.sabor

%p
  %b Preco:
  = @sorvete.preco

%p
  %b Cobertura:
  = @sorvete.cobertura


= link_to 'Editar', edit_sorvete_path(@sorvete)
= link_to 'Voltar', sorvetes_path